package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Tuesday, April 23, 2024 9:10:29 PM PDT
*/

public interface ReverseOperations 
{
  String capital (String str);
} // interface ReverseOperations
